@phone={{$dotenv TXTCONNECT_PHONE}}
@message=Hi you

POST {{$dotenv TXTCONNECT_ENDPOINT}}?action=send-sms HTTP/1.1
Content-type: application/json

{
    "api_key": "{{$dotenv TXTCONNECT_KEY}}",
    "to": "{{phone}}",
    "from": "{{$dotenv TXTCONNECT_FROM}}",
    "sms": "{{message}}",
    "response": "json",
    "unicode": true
}

###
@batch_no=

{{$dotenv TXTCONNECT_ENDPOINT}}?action=get-status&api_key={{$dotenv TXTCONNECT_KEY}}&batch_no={{batch_no}}&response=json

### RESPONSE OF GET STATUS
# {
#     "id": 1,
#     "batch_no": "",
#     "from": "",
#     "phone": "",
#     "sms": "",
#     "amount": 1,
#     "segments": 1,
#     "status": "Message delivered Successfully",
#     "type": null
# }